name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
          --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:sha-${{ github.sha }} \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --add-cloudsql-instances=${{ secrets.CLOUDSQL_INSTANCE }} \
          --allow-unauthenticated \
          --set-env-vars JDBC_DATABASE_USERNAME=${{ secrets.JDBC_DATABASE_USERNAME }},JDBC_DATABASE_PASSWORD=${{ secrets.JDBC_DATABASE_PASSWORD }},JDBC_DATABASE_URL='${{ secrets.JDBC_DATABASE_URL }}',KAFKA_BOOTSTRAP_SERVER='${{ secrets.KAFKA_BOOTSTRAP_SERVER }}',CLUSTER_API_KEY='${{ secrets.CLUSTER_API_KEY }}',CLUSTER_API_SECRET='${{ secrets.CLUSTER_API_SECRET }}',DEPLOYMENT_TIMESTAMP=$(date +%s)